[package]
name = "video-player-rs"
version = "0.1.0"
authors = ["Olivia <olivia_github@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-next = "4.3.0"
sdl2 = "0.34.5"